<a href="https://colab.research.google.com/github/tan003600/Data-Structure/blob/main/Linear_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
arr = [None] * 4
print(arr)
print(arr[0])

[None, None, None, None]
None


In [ ]:
import numpy as np
arr=[0]*4
print(arr)

[0, 0, 0, 0]


In [ ]:
arr[0] = 'Sarika'
print(arr)
arr[1] = 'Bhaskar'
arr[2] = 'Wasif'
arr[3] = 'Mahim'
print(arr)

['Sarika', None, None, None]
['Sarika', 'Bhaskar', 'Wasif', 'Mahim']


In [ ]:
for x in arr:
  print(x)


Sarika
Bhaskar
Wasif
Mahim


In [ ]:
for i in range(0, len(arr), 1):
  print(arr[i])

Sarika
Bhaskar
Wasif
Mahim


In [ ]:
new_arr = [None]*8
print(new_arr)

[None, None, None, None, None, None, None, None]


In [ ]:
def resize_arr(old_arr, new_arr_size):
  new_arr = [None]*new_arr_size

  for i in range(0, len(old_arr), 1):
    new_arr[ i] = old_arr[i]

  return new_arr

In [ ]:
arr = [None] * 4

arr[0] = 'Sarika'
arr[1] = 'Bhaskar'
arr[2] = 'Wasif'
arr[3] = 'Mahim'

print(arr)
arr = resize_arr(arr, 8)
print(arr)

['Sarika', 'Bhaskar', 'Wasif', 'Mahim']
['Sarika', 'Bhaskar', 'Wasif', 'Mahim', None, None, None, None]


In [ ]:
arr = [None]*5
print(arr)

[None, None, None, None, None]


In [ ]:
arr[0] = 'Niha'
arr[1] = 'Shuvro'
arr[2] = 'Torsha'
arr[3] = 'Rahin'
arr[4]= 'Sayeed'

print(arr)

['Niha', 'Shuvro', 'Torsha', 'Rahin', 'Sayeed']


In [ ]:
#####Not allowed#######
for x in arr:
  print(x)

Niha
Shuvro
Torsha
Rahin
Sayeed


In [ ]:
print("idx", "elem")
print("-----------")
for i in range(0, len(arr), 1):
  print(i+1, ".", arr[i])

idx elem
-----------
1 . Niha
2 . Shuvro
3 . Torsha
4 . Rahin
5 . Sayeed


In [ ]:
def resize_arr(old_arr, new_size):
  new_arr = [None]*new_size

  for i in range(0, len(old_arr), 1):
    new_arr[i] = old_arr[i]



In [ ]:
arr = [10, 20 , 30 , 40 , 50]
arr = resize_arr(arr, 8)
print(arr)

None


In [ ]:
#forward itr
arr = [10, 20, 30, 40, 50]
for i in range(0, len(arr), 1):
  print(arr[i], end= " ")

10 20 30 40 50 

In [ ]:
#backward itr
for i in range(len(arr)-1, -1, -1):
  print(arr[i], end=" ")

50 40 30 20 10 

In [ ]:
#array_reverse
def reverse_array(source):
  copy_arr = [None]*len(source) #out of place array, extra memory, hence out of place
  j=0
  for i in range(len(source)-1, -1, -1):
    copy_arr[j] = source[i]
    j+=1

  return copy_arr

In [ ]:
rev_arr = reverse_array(arr)
print(rev_arr)

[50, 40, 30, 20, 10]


In [ ]:
def reverse_in_place(source):
  l = len(source)
  for i in range(0, l//2, 1):
    temp = source[i]
    source[i] = source[l-1-i]
    source[l-1-i] = temp

  return source

In [ ]:
print(reverse_in_place(arr))

[50, 40, 30, 20, 10]


In [ ]:
arr = [10, 20, 30 ,40 ,50]
def shift_left(source):
  l = len(source)
  for i in range(0, l-1, 1):
    source[i] = source[i+1]

  source[l-1] = None

  return source

print(shift_left(arr))

[20, 30, 40, 50, None]


In [ ]:
arr = [10, 20, 30 ,40,50]

def rotate_left(source, k):
    l = len(source)

    temp = source[0]
    for i in range(0, l-1, 1):
      source[i] = source[i+1]

    source[l-1] = temp

    return source

print(rotate_left(arr, 2))

[20, 30, 40, 50, 10]


In [ ]:
#insert element
arr = [10, 20, 30 ,40,50, None, None]

def insert(arr, size, element, index):

  for i in range(size, index, -1):
    arr[i] = arr[i-1]

  arr[index] = element

  return arr

print(insert(arr, 5, 35, 3))

[10, 20, 30, 35, 40, 50, None]


In [ ]:
arr = [10, 20, 30 ,40 ,50]

def shift_right(source):
    l=len(source)

    for i in range(l-1, -1, -1):
        source[i]=source[i-1]

    source[0]=None

    return source

print(shift_right(arr))

[None, 10, 20, 30, 40]


In [ ]:
arr = [10, 20, 30 ,40 ,50]

def rotate_right(source):
    l=len(source)
    temp=source[l-1]
    for i in range(l-1,-1,-1):
        source[i]=source[i-1]

    source[0]=temp

    return source

print(rotate_right(arr))

[50, 10, 20, 30, 40]


In [ ]:
import numpy as np
new=np.zeros(5,dtype=int)
print(new)

[0 0 0 0 0]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
x=3
arr=[int],x,5
print(arr)

([<class 'int'>], 3, 5)


In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
a=np.array([1,2,3,4,5])

def it(arr):
    for i in range(len(arr)):
        print (arr[i])

(it(a))

1
2
3
4
5


In [ ]:
a=np.array([1,2,3,4,5])
def it(arr):
    i=0
    while i<len(a):
        print (arr[i])
        i+=1

print(it(a))

1
2
3
4
5
None


In [ ]:
def it_rev(arr):
    for i in range(len(arr)-1,-1,-1):
        print(arr[i])

it_rev(a)

5
4
3
2
1


In [ ]:
def it_rev(arr):
    i=len(arr)-1
    while i>-1:
        print(arr[i])
        i-=1

it_rev(a)


5
4
3
2
1


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
x=len(b)-1
for i in range(len(a)):
    print(a[i],',',b[x])
    x-=1

1 , 40
2 , 30
3 , 20
4 , 10


In [ ]:
import numpy as np
a=np.array([1,2,3,4])

def leftshift(arr,idx):
    for i in range(idx,len(arr)-1):
        arr[i]=arr[i+1]
    arr[len(arr)-1]=0
    return arr

def leftrotate(arr,idx):
    temp=arr[0]
    for i in range(idx,len(arr)-1):
        arr[i]=arr[i+1]
    arr[len(arr)-1]=temp
    return arr

print(leftshift(a,0))

print(leftrotate(a,0))

[2 3 4 0]
[3 4 0 2]


In [ ]:
import numpy as np
a=np.array([1,2,3,4])

def rightshift(arr,idx):
    for i in range(len(arr)-1,idx,-1):
        arr[i]=arr[i-1]
    arr[idx]=0
    return arr

def rightrotate(arr,idx):
    temp=arr[len(arr)-1]
    for i in range(len(arr)-1,idx,-1):
        arr[i]=arr[i-1]
    arr[idx]=temp
    return arr

print(rightshift(a,0))

print(rightrotate(a,0))

[0 1 2 3]
[3 0 1 2]


In [ ]:
import numpy as np
a=np.array([1,2,3,4])

def insert(arr,idx,elem):
    for i in range(len(arr)-1,idx,-1):
        arr[i]=arr[i-1]
    arr[idx]=elem
    return arr

print(insert(a,2,10))

[ 1  2 10  3]


In [1]:
import numpy as np
arr=np.array([0]*5,dtype=int)
print(arr)

[0 0 0 0 0]
